source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '4.0.3'

gem 'actionpack-action_caching'
gem 'activerecord-import'
gem 'actionpack-page_caching'
gem 'active_model_serializers'
gem 'activerecord-session_store'
gem 'addressable'
gem 'amoeba'
gem 'angularjs-rails', '~> 1.2.14'
gem 'autonumeric-rails'
gem 'aws-sdk'
gem 's3_direct_upload'
gem 'bootsy'
gem 'canable'
gem 'carrierwave'
gem 'coffee-rails'
gem "compass-rails", "~> 1.1.3"
gem 'dalli'
gem 'dotenv-rails'
gem 'fog'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'gravatar_image_tag'
gem 'haml'
#gem 'html5_validators'
#gem 'ims-lti'
gem 'jbuilder'
gem 'jquery-rails', '~> 2.0'
gem 'json'
gem 'kiqstand', :git => 'https://github.com/mongoid/kiqstand.git'
gem 'markerb'
gem 'mini_magick'
gem 'minitest-rails'
gem 'mongoid', :git => 'https://github.com/mongoid/mongoid.git'
gem 'ng-rails-csrf'
gem 'nokogiri', '1.6.0'
gem 'oink'
gem 'omniauth'
gem 'omniauth-kerberos'
gem 'omniauth-lti'
gem 'pacecar'
gem 'pg'
gem 'protected_attributes'
gem 'puma'
gem 'rails_autolink'
gem 'rdiscount'
gem 'responders'
gem 'rollbar'
gem 'sampler'
gem 'sanitize'
gem 'sass-rails', '~> 4.0.0.beta1'
gem 'select2-rails'
gem 'sendgrid'
gem 'sidekiq'
gem 'simple_form', '~> 3.0.0.rc'
gem 'sorcery'
gem 'timelineJS-rails', '~> 1.1.5'
gem 'uglifier'
gem 'whenever'
gem 'newrelic_rpm'
gem 'sinatra', '>= 1.3.0', :require => nil

group :development do
  gem 'haml-rails'
  gem 'valid_attribute'
  gem 'quiet_assets'
  gem 'foreman'
  gem 'rack-mini-profiler', require: false
  gem 'rubystats'
  gem 'spring'
  gem 'byebug'
  # gem 'guard-spring'
end

group :test do
  gem 'faker'
  gem 'capybara', '~> 2.1.0'
  gem 'database_cleaner', "~> 1.0.1"
  gem 'launchy'
  gem 'selenium-webdriver'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'factory_girl_rails', '~> 4.2.1'
end

